require("dotenv").config();

const mongoose = require("../src/models/db");
const City = require("../src/models/City");
const Country = require("../src/models/Country");
const CultureNote = require("../src/models/CultureNote");
const Favorite = require("../src/models/Favorite");
const Hotel = require("../src/models/Hotel");
const LocalGuide = require("../src/models/LocalGuide");
const Mosque = require("../src/models/Mosque");
const Place = require("../src/models/Place");
const Restaurant = require("../src/models/Restaurant");
const Review = require("../src/models/Review");
const TransportOption = require("../src/models/TransportOption");
const TravelExpense = require("../src/models/TravelExpense");
const TravelItinerary = require("../src/models/TravelItinerary");
const User = require("../src/models/User");
const VisaInfo = require("../src/models/VisaInfo");

const resetCollections = async () => {
  await Promise.all([
    City.deleteMany({}),
    Country.deleteMany({}),
    CultureNote.deleteMany({}),
    Favorite.deleteMany({}),
    Hotel.deleteMany({}),
    LocalGuide.deleteMany({}),
    Mosque.deleteMany({}),
    Place.deleteMany({}),
    Restaurant.deleteMany({}),
    Review.deleteMany({}),
    TransportOption.deleteMany({}),
    TravelExpense.deleteMany({}),
    TravelItinerary.deleteMany({}),
    User.deleteMany({}),
    VisaInfo.deleteMany({}),
  ]);
};

const seed = async () => {
  await resetCollections();

  const users = await User.insertMany([
    {
      name: "Sohail Khan",
      email: "sohail@example.com",
      password: "password123",
      role: "admin",
      phone: "+91 90000 10001",
      avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e",
    },
    {
      name: "Aisha Rahman",
      email: "aisha@example.com",
      password: "password123",
      role: "traveler",
      phone: "+91 90000 10002",
      avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
    },
    {
      name: "Yusuf Ali",
      email: "yusuf@example.com",
      password: "password123",
      role: "localGuide",
      phone: "+971 50000 10003",
      avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d",
    },
    {
      name: "Mariam Noor",
      email: "mariam@example.com",
      password: "password123",
      role: "localGuide",
      phone: "+90 53000 10004",
      avatarUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80",
    },
  ]);

  const countries = await Country.insertMany([
    {
      name: "United Arab Emirates",
      code: "AE",
      continent: "Asia",
      description: "Modern Gulf destination with excellent transport, luxury stays, and easy halal options.",
      currency: "AED",
      languages: ["Arabic", "English"],
      bestTimeToVisit: "November to March",
      safetyLevel: "high",
    },
    {
      name: "Turkey",
      code: "TR",
      continent: "Europe/Asia",
      description: "Historic cities, Ottoman architecture, coastal towns, and strong Muslim travel infrastructure.",
      currency: "TRY",
      languages: ["Turkish", "English"],
      bestTimeToVisit: "April to June, September to October",
      safetyLevel: "medium",
    },
    {
      name: "Malaysia",
      code: "MY",
      continent: "Asia",
      description: "Family-friendly country with diverse food, rainforests, beaches, and easy prayer facilities.",
      currency: "MYR",
      languages: ["Malay", "English", "Tamil"],
      bestTimeToVisit: "March to October",
      safetyLevel: "high",
    },
    {
      name: "Morocco",
      code: "MA",
      continent: "Africa",
      description: "Rich medinas, desert journeys, mountain towns, and deeply rooted Islamic heritage.",
      currency: "MAD",
      languages: ["Arabic", "French", "Berber"],
      bestTimeToVisit: "March to May, September to November",
      safetyLevel: "medium",
    },
  ]);

  const [uae, turkey, malaysia, morocco] = countries;

  const cities = await City.insertMany([
    {
      name: "Dubai",
      country: uae._id,
      description: "A polished city for families, business travelers, shopping, beaches, and modern attractions.",
      latitude: 25.2048,
      longitude: 55.2708,
      popularFor: ["shopping", "architecture", "family attractions"],
      muslimPopulationNote: "Prayer rooms and mosques are available across malls, hotels, and attractions.",
      bestTimeToVisit: "Winter",
    },
    {
      name: "Istanbul",
      country: turkey._id,
      description: "A layered city of mosques, bazaars, Bosphorus views, museums, and Ottoman heritage.",
      latitude: 41.0082,
      longitude: 28.9784,
      popularFor: ["history", "mosques", "food"],
      muslimPopulationNote: "Mosques are central to daily life and easy to find across the city.",
      bestTimeToVisit: "Spring and autumn",
    },
    {
      name: "Kuala Lumpur",
      country: malaysia._id,
      description: "A green capital with towers, markets, halal dining, family attractions, and good transit.",
      latitude: 3.139,
      longitude: 101.6869,
      popularFor: ["food", "shopping", "city breaks"],
      muslimPopulationNote: "Halal food and prayer facilities are widely available.",
      bestTimeToVisit: "March to October",
    },
    {
      name: "Marrakesh",
      country: morocco._id,
      description: "A colorful base for souks, riads, gardens, historic quarters, and desert trips.",
      latitude: 31.6295,
      longitude: -7.9811,
      popularFor: ["souks", "riads", "culture"],
      muslimPopulationNote: "Traditional mosques and Islamic culture shape the old city rhythm.",
      bestTimeToVisit: "Spring",
    },
  ]);

  const [dubai, istanbul, kualaLumpur, marrakesh] = cities;

  const mosques = await Mosque.insertMany([
    {
      name: "Jumeirah Mosque",
      city: dubai._id,
      country: uae._id,
      address: "Jumeirah Beach Road, Dubai",
      location: { lat: 25.2339, lng: 55.2652 },
      capacity: 1300,
      sect: "sunni",
      facilities: ["wudu", "women_area", "parking"],
      jummahTime: "13:15",
      description: "Iconic mosque known for visitor programs and beautiful Fatimid-inspired architecture.",
      images: ["https://images.unsplash.com/photo-1512453979798-5ea266f8880c"],
    },
    {
      name: "Sultan Ahmed Mosque",
      city: istanbul._id,
      country: turkey._id,
      address: "Sultanahmet, Istanbul",
      location: { lat: 41.0054, lng: 28.9768 },
      capacity: 10000,
      sect: "sunni",
      facilities: ["wudu", "women_area", "classes"],
      jummahTime: "13:05",
      description: "Historic mosque famous for its domes, minarets, and blue tile interior.",
      images: ["https://images.unsplash.com/photo-1524231757912-21f4fe3a7200"],
    },
    {
      name: "Masjid Negara",
      city: kualaLumpur._id,
      country: malaysia._id,
      address: "Jalan Perdana, Kuala Lumpur",
      location: { lat: 3.1412, lng: 101.6915 },
      capacity: 15000,
      sect: "sunni",
      facilities: ["wudu", "women_area", "parking", "wheelchair_access"],
      jummahTime: "13:20",
      description: "Malaysia's national mosque with distinctive modernist Islamic architecture.",
      images: ["https://images.unsplash.com/photo-1596422846543-75c6fc197f07"],
    },
    {
      name: "Koutoubia Mosque",
      city: marrakesh._id,
      country: morocco._id,
      address: "Medina, Marrakesh",
      location: { lat: 31.6241, lng: -7.9936 },
      capacity: 20000,
      sect: "sunni",
      facilities: ["wudu", "library"],
      jummahTime: "13:30",
      description: "Landmark Marrakesh mosque with a minaret visible across the medina.",
      images: ["https://images.unsplash.com/photo-1548018560-c7196548e84d"],
    },
  ]);

  const places = await Place.insertMany([
    {
      name: "Dubai Frame",
      city: dubai._id,
      country: uae._id,
      category: "landmark",
      description: "A panoramic landmark framing views of old and new Dubai.",
      address: "Zabeel Park, Dubai",
      location: { lat: 25.2355, lng: 55.3003 },
      entryFee: 50,
      openingHours: "09:00 - 21:00",
      images: ["https://images.unsplash.com/photo-1518684079-3c830dcef090"],
      tags: ["skyline", "family", "viewpoint"],
    },
    {
      name: "Topkapi Palace",
      city: istanbul._id,
      country: turkey._id,
      category: "historic",
      description: "Ottoman palace complex with courtyards, treasury rooms, and sacred relics.",
      address: "Cankurtaran, Istanbul",
      location: { lat: 41.0115, lng: 28.9833 },
      entryFee: 950,
      openingHours: "10:00 - 16:00",
      images: ["https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b"],
      tags: ["ottoman", "museum", "heritage"],
    },
    {
      name: "Batu Caves",
      city: kualaLumpur._id,
      country: malaysia._id,
      category: "nature",
      description: "Limestone caves and colorful stairway north of Kuala Lumpur.",
      address: "Gombak, Selangor",
      location: { lat: 3.2379, lng: 101.684 },
      entryFee: 0,
      openingHours: "07:00 - 21:00",
      images: ["https://images.unsplash.com/photo-1573790387438-4da905039392"],
      tags: ["caves", "day trip", "photography"],
    },
    {
      name: "Jemaa el-Fnaa",
      city: marrakesh._id,
      country: morocco._id,
      category: "culture",
      description: "A lively central square with market stalls, food stands, and evening performances.",
      address: "Medina, Marrakesh",
      location: { lat: 31.6258, lng: -7.9891 },
      entryFee: 0,
      openingHours: "All day",
      images: ["https://images.unsplash.com/photo-1539020140153-e479b8c22e70"],
      tags: ["market", "food", "old city"],
    },
  ]);

  const hotels = await Hotel.insertMany([
    {
      name: "Crescent Marina Hotel",
      city: dubai._id,
      country: uae._id,
      address: "Dubai Marina, Dubai",
      location: { lat: 25.0801, lng: 55.1402 },
      starRating: 5,
      pricePerNight: 680,
      amenities: ["pool", "family rooms", "halal breakfast", "airport transfer"],
      muslimFriendlyScore: 9,
      nearbyMosques: [{ mosque: mosques[0]._id, distanceKm: 12 }],
      images: ["https://images.unsplash.com/photo-1566073771259-6a8506099945"],
    },
    {
      name: "Sultanahmet Heritage Stay",
      city: istanbul._id,
      country: turkey._id,
      address: "Sultanahmet, Istanbul",
      location: { lat: 41.0069, lng: 28.9784 },
      starRating: 4,
      pricePerNight: 190,
      amenities: ["breakfast", "family rooms", "walkable mosques"],
      muslimFriendlyScore: 8,
      nearbyMosques: [{ mosque: mosques[1]._id, distanceKm: 0.4 }],
      images: ["https://images.unsplash.com/photo-1551882547-ff40c63fe5fa"],
    },
    {
      name: "KL Central Suites",
      city: kualaLumpur._id,
      country: malaysia._id,
      address: "KL Sentral, Kuala Lumpur",
      location: { lat: 3.134, lng: 101.686 },
      starRating: 4,
      pricePerNight: 260,
      amenities: ["metro access", "halal dining", "gym"],
      muslimFriendlyScore: 9,
      nearbyMosques: [{ mosque: mosques[2]._id, distanceKm: 1.2 }],
      images: ["https://images.unsplash.com/photo-1564501049412-61c2a3083791"],
    },
    {
      name: "Riad Noor Courtyard",
      city: marrakesh._id,
      country: morocco._id,
      address: "Medina, Marrakesh",
      location: { lat: 31.629, lng: -7.989 },
      starRating: 4,
      pricePerNight: 145,
      amenities: ["courtyard", "breakfast", "local tours"],
      muslimFriendlyScore: 8,
      nearbyMosques: [{ mosque: mosques[3]._id, distanceKm: 0.8 }],
      images: ["https://images.unsplash.com/photo-1570213489059-0aac6626cade"],
    },
  ]);

  const restaurants = await Restaurant.insertMany([
    {
      name: "Al Fanar Restaurant",
      city: dubai._id,
      country: uae._id,
      cuisine: ["Emirati", "Middle Eastern"],
      halalStatus: "certified",
      priceRange: "mid",
      address: "Dubai Festival City",
      location: { lat: 25.221, lng: 55.3505 },
      phone: "+971 4 232 9966",
      rating: 4.6,
      popularDishes: ["machboos", "luqaimat"],
      images: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5"],
    },
    {
      name: "Bosphorus Kebab House",
      city: istanbul._id,
      country: turkey._id,
      cuisine: ["Turkish", "Grill"],
      halalStatus: "self_declared",
      priceRange: "budget",
      address: "Fatih, Istanbul",
      location: { lat: 41.012, lng: 28.965 },
      phone: "+90 212 000 1000",
      rating: 4.4,
      popularDishes: ["adana kebab", "lentil soup"],
      images: ["https://images.unsplash.com/photo-1540189549336-e6e99c3679fe"],
    },
    {
      name: "Nasi Kandar Central",
      city: kualaLumpur._id,
      country: malaysia._id,
      cuisine: ["Malay", "Indian Muslim"],
      halalStatus: "certified",
      priceRange: "budget",
      address: "Bukit Bintang, Kuala Lumpur",
      location: { lat: 3.1466, lng: 101.711 },
      phone: "+60 3 0000 1000",
      rating: 4.5,
      popularDishes: ["nasi kandar", "teh tarik"],
      images: ["https://images.unsplash.com/photo-1504674900247-0877df9cc836"],
    },
    {
      name: "Medina Tagine Kitchen",
      city: marrakesh._id,
      country: morocco._id,
      cuisine: ["Moroccan", "North African"],
      halalStatus: "self_declared",
      priceRange: "mid",
      address: "Medina, Marrakesh",
      location: { lat: 31.6265, lng: -7.989 },
      phone: "+212 524 000 100",
      rating: 4.7,
      popularDishes: ["lamb tagine", "harira"],
      images: ["https://images.unsplash.com/photo-1544025162-d76694265947"],
    },
  ]);

  const itineraries = await TravelItinerary.insertMany([
    {
      title: "Dubai Family Weekend",
      user: users[1]._id,
      country: uae._id,
      cities: [dubai._id],
      startDate: new Date("2026-01-10"),
      endDate: new Date("2026-01-13"),
      budget: 4200,
      days: [{ dayNumber: 1, date: new Date("2026-01-10"), city: dubai._id }],
      isPublic: true,
    },
    {
      title: "Istanbul Heritage Walk",
      user: users[0]._id,
      country: turkey._id,
      cities: [istanbul._id],
      startDate: new Date("2026-04-18"),
      endDate: new Date("2026-04-23"),
      budget: 2100,
      days: [{ dayNumber: 1, date: new Date("2026-04-18"), city: istanbul._id }],
      isPublic: true,
    },
    {
      title: "KL Food And City Break",
      user: users[1]._id,
      country: malaysia._id,
      cities: [kualaLumpur._id],
      startDate: new Date("2026-07-02"),
      endDate: new Date("2026-07-06"),
      budget: 1800,
      days: [{ dayNumber: 1, date: new Date("2026-07-02"), city: kualaLumpur._id }],
      isPublic: false,
    },
    {
      title: "Marrakesh Medina Escape",
      user: users[0]._id,
      country: morocco._id,
      cities: [marrakesh._id],
      startDate: new Date("2026-10-08"),
      endDate: new Date("2026-10-12"),
      budget: 1600,
      days: [{ dayNumber: 1, date: new Date("2026-10-08"), city: marrakesh._id }],
      isPublic: true,
    },
  ]);

  await Promise.all([
    VisaInfo.insertMany([
      {
        country: uae._id,
        passportCountry: "India",
        visaType: "Tourist Visa",
        applicationMode: "evisa",
        documentsRequired: ["passport", "photo", "return ticket"],
        processingTime: "3-5 working days",
        fee: { amount: 6500, currency: "INR" },
        officialWebsite: "https://u.ae",
        notes: "Check airline and emirate-specific requirements before travel.",
      },
      {
        country: turkey._id,
        passportCountry: "India",
        visaType: "Tourist e-Visa",
        applicationMode: "evisa",
        documentsRequired: ["passport", "valid supporting visa", "hotel booking"],
        processingTime: "Instant to 24 hours",
        fee: { amount: 43, currency: "USD" },
        officialWebsite: "https://www.evisa.gov.tr",
        notes: "Eligibility depends on supporting visa/residence permit rules.",
      },
      {
        country: malaysia._id,
        passportCountry: "India",
        visaType: "eVISA",
        applicationMode: "evisa",
        documentsRequired: ["passport", "photo", "flight booking", "hotel booking"],
        processingTime: "2-3 working days",
        fee: { amount: 3500, currency: "INR" },
        officialWebsite: "https://malaysiavisa.imi.gov.my",
        notes: "Review current entry rules before booking.",
      },
      {
        country: morocco._id,
        passportCountry: "India",
        visaType: "Tourist Visa",
        applicationMode: "embassy",
        documentsRequired: ["passport", "photo", "bank statement", "hotel booking"],
        processingTime: "7-10 working days",
        fee: { amount: 2200, currency: "INR" },
        officialWebsite: "https://www.consulat.ma",
        notes: "Embassy documentation may vary by jurisdiction.",
      },
    ]),
    CultureNote.insertMany([
      {
        title: "Ramadan Dining In Dubai",
        country: uae._id,
        city: dubai._id,
        category: "food",
        content: "Many hotels offer iftar buffets, but daytime dining rules and timings can differ during Ramadan.",
        tags: ["ramadan", "iftar", "families"],
      },
      {
        title: "Mosque Etiquette In Istanbul",
        country: turkey._id,
        city: istanbul._id,
        category: "religion",
        content: "Carry modest clothing, avoid prayer times for sightseeing, and follow posted visitor areas.",
        tags: ["mosques", "modesty", "heritage"],
      },
      {
        title: "Halal Food Confidence In KL",
        country: malaysia._id,
        city: kualaLumpur._id,
        category: "food",
        content: "Look for official halal certification, especially in malls and food courts.",
        tags: ["halal", "food courts", "families"],
      },
      {
        title: "Medina Bargaining Basics",
        country: morocco._id,
        city: marrakesh._id,
        category: "local_customs",
        content: "Bargaining is common in souks; agree clearly on prices before accepting services.",
        tags: ["souks", "shopping", "etiquette"],
      },
    ]),
    LocalGuide.insertMany([
      {
        user: users[2]._id,
        city: dubai._id,
        languages: ["Arabic", "English", "Hindi"],
        bio: "Family-friendly Dubai guide focused on heritage areas, mosques, food, and airport logistics.",
        expertise: ["culture", "food", "family_travel"],
        hourlyRate: 150,
        currency: "AED",
        availableDays: ["monday", "wednesday", "saturday"],
        contactWhatsapp: "+971500001003",
        rating: 4.8,
      },
      {
        user: users[3]._id,
        city: istanbul._id,
        languages: ["Turkish", "English"],
        bio: "Old city walking guide for Ottoman history, bazaars, and mosque visits.",
        expertise: ["history", "mosques", "shopping"],
        hourlyRate: 45,
        currency: "EUR",
        availableDays: ["tuesday", "thursday", "sunday"],
        contactWhatsapp: "+905300010004",
        rating: 4.7,
      },
      {
        user: users[2]._id,
        city: kualaLumpur._id,
        languages: ["Malay", "English", "Hindi"],
        bio: "Food and family-trip guide for Kuala Lumpur neighborhoods and day trips.",
        expertise: ["food", "transport", "family_travel"],
        hourlyRate: 180,
        currency: "MYR",
        availableDays: ["friday", "saturday"],
        contactWhatsapp: "+60120001003",
        rating: 4.6,
      },
      {
        user: users[3]._id,
        city: marrakesh._id,
        languages: ["Arabic", "French", "English"],
        bio: "Medina guide for souks, riads, gardens, and local customs.",
        expertise: ["culture", "shopping", "history"],
        hourlyRate: 40,
        currency: "EUR",
        availableDays: ["monday", "saturday", "sunday"],
        contactWhatsapp: "+212600010004",
        rating: 4.9,
      },
    ]),
    TransportOption.insertMany([
      {
        fromCity: dubai._id,
        toCity: istanbul._id,
        type: "flight",
        provider: "Emirates",
        estimatedDuration: "4h 45m",
        estimatedCost: 320,
        currency: "USD",
        bookingUrl: "https://www.emirates.com",
        notes: "Direct flights operate frequently.",
      },
      {
        fromCity: istanbul._id,
        toCity: marrakesh._id,
        type: "flight",
        provider: "Turkish Airlines",
        estimatedDuration: "5h",
        estimatedCost: 260,
        currency: "USD",
        bookingUrl: "https://www.turkishairlines.com",
        notes: "Check baggage rules for regional fares.",
      },
      {
        fromCity: kualaLumpur._id,
        toCity: dubai._id,
        type: "flight",
        provider: "Malaysia Airlines",
        estimatedDuration: "7h 10m",
        estimatedCost: 410,
        currency: "USD",
        bookingUrl: "https://www.malaysiaairlines.com",
        notes: "Overnight flight works well for families.",
      },
      {
        fromCity: marrakesh._id,
        toCity: istanbul._id,
        type: "flight",
        provider: "Royal Air Maroc",
        estimatedDuration: "4h 55m",
        estimatedCost: 290,
        currency: "USD",
        bookingUrl: "https://www.royalairmaroc.com",
        notes: "Seasonal pricing can change quickly.",
      },
    ]),
    TravelExpense.insertMany([
      {
        user: users[1]._id,
        itinerary: itineraries[0]._id,
        category: "hotel",
        amount: 1360,
        currency: "AED",
        spentAt: new Date("2026-01-11"),
        note: "Two nights at Crescent Marina Hotel.",
      },
      {
        user: users[0]._id,
        itinerary: itineraries[1]._id,
        category: "tickets",
        amount: 1900,
        currency: "TRY",
        spentAt: new Date("2026-04-19"),
        note: "Museum and palace tickets.",
      },
      {
        user: users[1]._id,
        itinerary: itineraries[2]._id,
        category: "food",
        amount: 240,
        currency: "MYR",
        spentAt: new Date("2026-07-03"),
        note: "Family dinner and snacks.",
      },
      {
        user: users[0]._id,
        itinerary: itineraries[3]._id,
        category: "shopping",
        amount: 780,
        currency: "MAD",
        spentAt: new Date("2026-10-09"),
        note: "Souk gifts and local crafts.",
      },
    ]),
    Review.insertMany([
      {
        user: users[1]._id,
        targetType: "Hotel",
        targetId: hotels[0]._id,
        rating: 5,
        comment: "Excellent family stay with easy food options and helpful staff.",
      },
      {
        user: users[0]._id,
        targetType: "Place",
        targetId: places[1]._id,
        rating: 5,
        comment: "Topkapi Palace was the highlight of the trip.",
      },
      {
        user: users[1]._id,
        targetType: "Restaurant",
        targetId: restaurants[2]._id,
        rating: 4,
        comment: "Fast, affordable, and reliable halal comfort food.",
      },
      {
        user: users[0]._id,
        targetType: "Mosque",
        targetId: mosques[3]._id,
        rating: 5,
        comment: "Beautiful landmark and easy to locate from the medina.",
      },
    ]),
    Favorite.insertMany([
      {
        user: users[1]._id,
        itemType: "Hotel",
        itemId: hotels[0]._id,
        notes: "Good choice for Dubai family trip.",
      },
      {
        user: users[0]._id,
        itemType: "Place",
        itemId: places[1]._id,
        notes: "Must include in Istanbul itinerary.",
      },
      {
        user: users[1]._id,
        itemType: "Restaurant",
        itemId: restaurants[2]._id,
        notes: "Easy halal meal near shopping area.",
      },
      {
        user: users[0]._id,
        itemType: "TravelItinerary",
        itemId: itineraries[3]._id,
        notes: "Save for autumn travel.",
      },
    ]),
  ]);

  console.log("Seed complete.");
  console.log("Login with: sohail@example.com / password123");
};

seed()
  .catch((error) => {
    console.error("Seed failed:", error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await mongoose.connection.close();
  });
